[package]
name = "osgate"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6.0"
serde_json = "1.0.128"
validator = "0.18.1"
xmlschema = "0.0.1"
